#!/bin/sh
echo "Miner Monitor 1.0.0.0"

miner1="root@192.168.34.11"
miner2="root@192.168.34.12"

mqttLoc="-h localhost"
mqttExtraParam="-u antminers -P mining"

while true; do


sleep 5s


SoftwareStat1=$(ssh $miner1 bmminer-api -o)
#echo "SoftwareStat1:$SoftwareStat1"


Hashrate1=${SoftwareStat1#*5s=}
Hashrate1=${Hashrate1%%,GHS*}
if [ "$OldHashrate1" != "$Hashrate1" ]; then
echo "Hashrate1: $Hashrate1"
mosquitto_pub $mqttLoc -t antminer/1/hashrate -m "$Hashrate1" -r $mqttExtraParam
OldHashrate1=$Hashrate1
fi


HardwareErrors1=${SoftwareStat1#*Hardware Errors=}
HardwareErrors1=${HardwareErrors1%%,Utility*}
if [ "$OldHardwareErrors1" != "$HardwareErrors1" ]; then
echo "HardwareErrors1: $HardwareErrors1"
mosquitto_pub $mqttLoc -t antminer/1/hardwareErrors -m "$HardwareErrors1" -r $mqttExtraParam
OldHardwareErrors1=$HardwareErrors1
fi


AcceptedShares1=${SoftwareStat1#*Accepted=}
AcceptedShares1=${AcceptedShares1%%,Rejected=*}
if [ "$OldAcceptedShares1" != "$AcceptedShares1" ]; then
echo "AcceptedShares1:$AcceptedShares1"
mosquitto_pub $mqttLoc -t antminer/1/acceptedShares -m "$AcceptedShares1" -r $mqttExtraParam
OldAcceptedShares1=$AcceptedShares1
fi


RejectedShares1=${SoftwareStat1#*Rejected=}
RejectedShares1=${RejectedShares1%%,Hardware Errors=*}
if [ "$OldRejectedShares1" != "$RejectedShares1" ]; then
echo "RejectedShares1:$RejectedShares1"
mosquitto_pub $mqttLoc -t antminer/1/rejectedShares -m "$RejectedShares1" -r $mqttExtraParam
OldRejectedShares1=$RejectedShares1
fi


SoftwareStat2=$(ssh $miner2 bmminer-api -o)
#echo "SoftwareStat2:$SoftwareStat2"


Hashrate2=${SoftwareStat2#*5s=}
Hashrate2=${Hashrate2%%,GHS*}
if [ "$OldHashrate2" != "$Hashrate2" ]; then
echo "Hashrate2: $Hashrate2"
mosquitto_pub $mqttLoc -t antminer/2/hashrate -m "$Hashrate2" -r  $mqttExtraParam
OldHashrate2=$Hashrate2
fi

HardwareErrors2=${SoftwareStat2#*Hardware Errors=}
HardwareErrors2=${HardwareErrors2%%,Utility*}
if [ "$OldHardwareErrors2" != "$HardwareErrors2" ]; then
echo "HardwareErrors2: $HardwareErrors2"
mosquitto_pub $mqttLoc -t antminer/2/hardwareErrors -m "$HardwareErrors2" -r $mqttExtraParam
OldHardwareErrors2=$HardwareErrors2
fi

AcceptedShares2=${SoftwareStat2#*Accepted=}
AcceptedShares2=${AcceptedShares2%%,Rejected=*}
if [ "$OldAcceptedShares2" != "$AcceptedShares2" ]; then
echo "AcceptedShares2:$AcceptedShares2"
mosquitto_pub $mqttLoc -t antminer/2/acceptedShares -m "$AcceptedShares2" -r $mqttExtraParam
OldAcceptedShares2=$AcceptedShares2
fi

RejectedShares2=${SoftwareStat2#*Rejected=}
RejectedShares2=${RejectedShares2%%,Hardware Errors=*}
if [ "$OldRejectedShares2" != "$RejectedShares2" ]; then
echo "RejectedShares2:$RejectedShares2"
mosquitto_pub $mqttLoc -t antminer/2/rejectedShares -m "$RejectedShares2" -r $mqttExtraParam
OldRejectedShares2=$RejectedShares2
fi


sleep 5s


HardwareStat1=$(ssh $miner1 bmminer-api -o stats)
#echo "HardwareStat1:$HardwareStat1"


Temps111=${HardwareStat1#*temp6=}
Temps111=${Temps111%%,temp7=*}
if [ "$OldTemps111" != "$Temps111" ]; then
echo "Temps111: $Temps111"
mosquitto_pub $mqttLoc -t antminer/1/temps/chain6/chip1 -m "$Temps111" -r $mqttExtraParam
OldTemps111=$Temps111
fi



Temps211=${HardwareStat1#*temp7=}
Temps211=${Temps211%%,temp8=*}
if [ "$OldTemps211" != "$Temps211" ]; then
echo "Temps211: $Temps211"
mosquitto_pub $mqttLoc -t antminer/1/temps/chain7/chip1 -m "$Temps211" -r $mqttExtraParam
OldTemps211=$Temps211
fi


Temps311=${HardwareStat1#*temp8=}
Temps311=${Temps311%%,temp9=*}
if [ "$OldTemps311" != "$Temps311" ]; then
echo "Temps311: $Temps311"
mosquitto_pub $mqttLoc -t antminer/1/temps/chain8/chip1 -m "$Temps311" -r $mqttExtraParam
OldTemps311=$Temps311
fi

Temps121=${HardwareStat1#*temp2_6=}
Temps121=${Temps121%%,temp2_7=*}
if [ "$OldTemps121" != "$Temps121" ]; then
echo "Temps121: $Temps121"
mosquitto_pub $mqttLoc -t antminer/1/temps/chain6/chip2 -m "$Temps121" -r $mqttExtraParam
OldTemps121=$Temps121
fi


Temps221=${HardwareStat1#*temp2_7=}
Temps221=${Temps221%%,temp2_8=*}
if [ "$OldTemps221" != "$Temps221" ]; then
echo "Temps221: $Temps221"
mosquitto_pub $mqttLoc -t antminer/1/temps/chain7/chip2 -m "$Temps221" -r $mqttExtraParam
OldTemps221=$Temps221
fi


Temps321=${HardwareStat1#*temp2_8=}
Temps321=${Temps321%%,temp2_9=*}
if [ "$OldTemps321" != "$Temps321" ]; then
echo "Temps321: $Temps321"
mosquitto_pub $mqttLoc -t antminer/1/temps/chain8/chip2 -m "$Temps321" -r $mqttExtraParam
OldTemps321=$Temps321
fi

Asics11=${HardwareStat1#*chain_acs6= }
Asics11=${Asics11%%,chain_acs7=*}
if [ "$OldAsics11" != "$Asics11" ]; then
echo "Asics11: $Asics11"
mosquitto_pub $mqttLoc -t antminer/1/asics/chain6 -m "$Asics11" -r $mqttExtraParam
OldAsics11=$Asics11
fi


Asics21=${HardwareStat1#*chain_acs7= }
Asics21=${Asics21%%,chain_acs8=*}
if [ "$OldAsics21" != "$Asics21" ]; then
echo "Asics21: $Asics21"
mosquitto_pub $mqttLoc -t antminer/1/asics/chain7 -m "$Asics21" -r $mqttExtraParam
OldAsics21=$Asics21
fi


Asics31=${HardwareStat1#*chain_acs8= }
Asics31=${Asics31%%,chain_acs9=*}
if [ "$OldAsics31" != "$Asics31" ]; then
echo "Asics31: $Asics31"
mosquitto_pub $mqttLoc -t antminer/1/asics/chain8 -m "$Asics31" -r $mqttExtraParam
OldAsics31=$Asics31
fi


Fan11=${HardwareStat1#*fan3=}
Fan11=${Fan11%%,fan4=*}
if [ "$OldFan11" != "$Fan11" ]; then
echo "Fan11: $Fan11"
mosquitto_pub $mqttLoc -t antminer/1/fan3 -m "$Fan11" -r $mqttExtraParam
OldFan11=$Fan11
fi


Fan21=${HardwareStat1#*fan6=}
Fan21=${Fan21%%,fan7=*}
if [ "$OldFan21" != "$Fan21" ]; then
echo "Fan21: $Fan21"
mosquitto_pub $mqttLoc -t antminer/1/fan3 -m "$Fan21" -r $mqttExtraParam
OldFan21=$Fan21
fi

HardwareStat2=$(ssh $miner2 bmminer-api -o stats)
#echo "HardwareStat1:$HardwareStat1"


Temps112=${HardwareStat2#*temp6=}
Temps112=${Temps112%%,temp7=*}
if [ "$OldTemps112" != "$Temps112" ]; then
echo "Temps112: $Temps112"
mosquitto_pub $mqttLoc -t antminer/2/temps/chain6/chip1 -m "$Temps112" -r $mqttExtraParam
OldTemps112=$Temps112
fi



Temps212=${HardwareStat2#*temp7=}
Temps212=${Temps212%%,temp8=*}
if [ "$OldTemps212" != "$Temps212" ]; then
echo "Temps212: $Temps212"
mosquitto_pub $mqttLoc -t antminer/2/temps/chain7/chip1 -m "$Temps212" -r $mqttExtraParam
OldTemps212=$Temps212
fi


Temps312=${HardwareStat2#*temp8=}
Temps312=${Temps312%%,temp9=*}
if [ "$OldTemps312" != "$Temps312" ]; then
echo "Temps312: $Temps312"
mosquitto_pub $mqttLoc -t antminer/2/temps/chain8/chip1 -m "$Temps312" -r $mqttExtraParam
OldTemps312=$Temps312
fi

Temps122=${HardwareStat2#*temp2_6=}
Temps122=${Temps122%%,temp2_7=*}
if [ "$OldTemps122" != "$Temps122" ]; then
echo "Temps122: $Temps122"
mosquitto_pub $mqttLoc -t antminer/2/temps/chain6/chip2 -m "$Temps122" -r $mqttExtraParam
OldTemps122=$Temps122
fi


Temps222=${HardwareStat2#*temp2_7=}
Temps222=${Temps222%%,temp2_8=*}
if [ "$OldTemps222" != "$Temps222" ]; then
echo "Temps222: $Temps222"
mosquitto_pub $mqttLoc -t antminer/2/temps/chain7/chip2 -m "$Temps222" -r $mqttExtraParam
OldTemps222=$Temps222
fi


Temps322=${HardwareStat2#*temp2_8=}
Temps322=${Temps322%%,temp2_9=*}
if [ "$OldTemps322" != "$Temps322" ]; then
echo "Temps322: $Temps322"
mosquitto_pub $mqttLoc -t antminer/2/temps/chain8/chip2 -m "$Temps322" -r $mqttExtraParam
OldTemps322=$Temps322
fi

Asics12=${HardwareStat2#*chain_acs6= }
Asics12=${Asics12%%,chain_acs7=*}
if [ "$OldAsics12" != "$Asics12" ]; then
echo "Asics12: $Asics12"
mosquitto_pub $mqttLoc -t antminer/2/asics/chain6 -m "$Asics12" -r $mqttExtraParam
OldAsics12=$Asics12
fi


Asics22=${HardwareStat2#*chain_acs7= }
Asics22=${Asics22%%,chain_acs8=*}
if [ "$OldAsics22" != "$Asics22" ]; then
echo "Asics22: $Asics22"
mosquitto_pub $mqttLoc -t antminer/2/asics/chain7 -m "$Asics22" -r $mqttExtraParam
OldAsics22=$Asics22
fi


Asics32=${HardwareStat2#*chain_acs8= }
Asics32=${Asics32%%,chain_acs9=*}
if [ "$OldAsics32" != "$Asics32" ]; then
echo "Asics32: $Asics32"
mosquitto_pub $mqttLoc -t antminer/2/asics/chain8 -m "$Asics32" -r $mqttExtraParam
OldAsics32=$Asics32
fi


Fan12=${HardwareStat2#*fan3=}
Fan12=${Fan12%%,fan4=*}
if [ "$OldFan12" != "$Fan12" ]; then
echo "Fan12: $Fan12"
mosquitto_pub $mqttLoc -t antminer/2/fan3 -m "$Fan12" -r $mqttExtraParam
OldFan12=$Fan12
fi


Fan22=${HardwareStat2#*fan6=}
Fan22=${Fan22%%,fan7=*}
if [ "$OldFan22" != "$Fan22" ]; then
echo "Fan22: $Fan22"
mosquitto_pub $mqttLoc -t antminer/2/fan6 -m "$Fan22" -r $mqttExtraParam
OldFan22=$Fan22
fi


done


